[package]
name = "mfind"
version = "0.1.0"
edition = "2024"

[dependencies]
blake3 = "1.8.7"
serde = { version = "1.0.229", features = ["derive"] }
serde_json = "1.0.151"
walkdir = "2.5.0"

[target."cfg(windows)".dependencies]
windows = { version = "0.62.2", features = ["Win32_Foundation", "Win32_Storage_FileSystem", "Win32_System_IO", "Win32_System_Ioctl", "Win32_Security", "Win32_UI_Shell", "Win32_UI_WindowsAndMessaging"] }

[profile.release]
opt-level = 3
lto = true
codegen-units = 1
panic = "abort"
strip = true
